version: '3'

services:
  mysql:
    container_name: bus-data
    image: mysql/mysql-server:8.0.31
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: bus-data
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"